Repository ThalesGroup/GeoTools, pull requests merged in 2024-10, with the labels that each got.

#7 updating baseline with Unit fork, awaiting pull request
  BaselineOfGeoTools/BaselineOfGeoTools.class.st
Labels: refactoring

#10 Fix #9
  .github/workflows/Pharo11CI.yml
  .github/workflows/Pharo12CI.yml
  .project
  .smalltalk.ston
  src/.properties
  src/BaselineOfGeoTools/BaselineOfGeoTools.class.st
  src/BaselineOfGeoTools/package.st
  src/GeoTools-Tests/AbsoluteCoordinatesTest.class.st
  src/GeoTools-Tests/CoordinatesTests.class.st
  src/GeoTools-Tests/GeoToolsExtensionsTests.class.st
  src/GeoTools-Tests/GeodesicUtilitiesTest.class.st
  src/GeoTools-Tests/KinematicsTests.class.st
  src/GeoTools-Tests/package.st
  src/GeoTools/AbsoluteCoordinates.class.st
  src/GeoTools/CartesianCoordinates.class.st
  src/GeoTools/GeodesicUtilities.class.st
  src/GeoTools/Kinematics.class.st
  src/GeoTools/ManifestGeoTools.class.st
  src/GeoTools/Number.extension.st
  src/GeoTools/Point.extension.st
  src/GeoTools/PolarCoordinates.class.st
  src/GeoTools/WGS84.class.st
  src/GeoTools/package.st
Labels: technical work, ci/cd

#11 Change OpenSmock branch
  src/BaselineOfGeoTools/BaselineOfGeoTools.class.st
Labels: technical work
